### ISSUE TITLE
Chatbot flow diagrams

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/your-sanctuary#2]
@fiammapather it would be great to see where you're at with the diagrams for the chat flow. 

Could you share the draw.io diagram here?

**Comment by fiammapather** [comment]
@lucymk Ok will do
![image](https://user-images.githubusercontent.com/44403952/47365106-be5c5b00-d6d2-11e8-8c6c-4d4df1a2f8c1.png)

**Comment by lucymk** [comment]
We've chatted about this, so I'm closing this issue :)
