### ISSUE TITLE
Feedback from user testing - Age 16 Disclaimer 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#55]
Please can the text below be added to the second page so it says: 

Supporting survivors of domestic abuse
We offer sanctuary, support and empowerment to anyone affected by Domestic Abuse.
Your safety is very important to us.

*Please note - if you are under 16 we will not be able to chat with you using this service. Please visit - www.thehideout.org.uk for more information
By clicking ‘Next’ you are confirming you are over the age of 16

**Comment by lucymk** [comment]
hi @joannayoungs can you clarify, do you want this added to the chat page?

![screen shot 2018-11-19 at 12 04 01](https://user-images.githubusercontent.com/13594621/48706187-65a9b080-ebf3-11e8-8159-2256c237891f.png)

or to the first sign up page?

![screen shot 2018-11-19 at 12 04 23](https://user-images.githubusercontent.com/13594621/48707708-35184580-ebf8-11e8-8f5e-808d19865a34.png)

Thanks

**Comment by joannayoungs** [comment]
Please see issue #61
