### ISSUE TITLE
Feedback from user testing - disclaimer regarding website links and safety 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#57]
We need to put a disclaimer regarding providing website links somewhere at the start of the chat 

Could we trial this to the left of the page 

Please note - during the chat you may be sent links to external websites for more information and advice. For your safety, we recommend that you delete your web history once you have finished your chat. If you need advice on how to do this then please visit https://www.yoursanctuary.org.uk/cover-your-tracks-online.

**Comment by lucymk** [comment]
@joannayoungs this is done, please test and close

**Comment by joannayoungs** [comment]
Closing as all works well
