### ISSUE TITLE
Forgotten code email 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#59]
Email sent when code has been forgotten: 

From: Sanctuary Chat  ( or something similar when Fiamma has confirmed the domain this will be sent from) 

Subject: Forgotten code 

Body: Please see below for your code 
          ABC123 

We want to keep this really simple with no branding

**Comment by lucymk** [comment]
This also should be working now, @joannayoungs please check and close the issue if all good 👍

**Comment by joannayoungs** [comment]
@lucymk  can you update the message when you click "i forgot my code" so this says the same about the email being simple and unbranded and not a promotional code for a prize please :)

**Comment by joannayoungs** [comment]
@lucymk also for the confirmation thumb pop up to say the same as that currently still also says about the promotional code

**Comment by lucymk** [comment]
Good catches @joannayoungs ! These have been updated now.

**Comment by lucymk** [comment]
@joannayoungs please close if this is all good now 😃
