### ISSUE TITLE
Forgotten code wording for screen 1 and 2 of the chat 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#61]
Page 1 
Supporting survivors of domestic abuse
We offer sanctuary, support and empowerment to anyone affected by Domestic Abuse.
To access our chat service, you will need a unique code which we will now issue for you.
You will need to remember this code to access your conversation if you wish to pick up where you left off

NEXT 

Page 2 
If you would like us to send you a reminder email should you forget your code then please provide your email address below.
We will never use your email address other than to remind you of your code. Your reminder email will appear as a simple unbranded message in your inbox 
If you would prefer not to give us your email address and you forget your code you will have to begin a new chat.

EMAIL  ---  SKIP THIS STEP

**Comment by joannayoungs** [comment]
@lucymk  could you add it to page 1 so it says: 

Supporting survivors of domestic abuse
We offer sanctuary, support and empowerment to anyone affected by Domestic Abuse.
To access our chat service, you will need a unique code which we will now issue for you.
You will need to remember this code to access your conversation if you wish to pick up where you left off
Please note, if you are under 16 we will not be able to chat with you using this service. Please visit - www.thehideout.org.uk for more information
By clicking ‘Next’ you are confirming you are over the age of 16

NEXT

**Comment by lucymk** [comment]
This has been done, you can check it on the staging site now @joannayoungs and close this issue if you approve! 😃

**Comment by joannayoungs** [comment]
Closing as clear and works well
