### ISSUE TITLE
Crisp account

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/your-sanctuary#64]
@joannayoungs @fiammapather your Crisp free trial has run out, which means I'm unable to access the bot or many other features - that's also why it's not working when you're testing it on the website. If you could provide payment details to start your subscription as soon as possible that would be amazing!

**Comment by joannayoungs** [comment]
@lucymk  just tried to call you but obviously you're busy. Just wanted to check, which level of the Crisp packages do we need? There is three different packages, do we need the most advanced one?

**Comment by lucymk** [comment]
Ah, sorry @joannayoungs! Feel free to call back if you want to chat, my phone is next to me now 😄 

Yes it is the most advanced one - I think that's usually 99/month but with your discount should only be 50/month

**Comment by joannayoungs** [comment]
Not a problem, Fiamma has paid for it all so should be good to go!

**Comment by lucymk** [comment]
This has been done, so I'm closing the issue 👍
