### ISSUE TITLE
Advisor online in chat and offline on the webpage 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#66]
Hi @lucymk when I've been on the staging of the app I've noticed that the chat says that the chat is online but the little icon showing the advisor is red saying there is no one available. 
The chat runs you through it as though it is available. 
Is this just because we are testing it?

**Comment by lucymk** [comment]
@joannayoungs yes, this is because there are people online testing the app. I've turned on the setting now where availability is only set by the opening hours, not by whether anyone is online, so this shouldn't be happening anymore.
