### ISSUE TITLE
Pre scripted text - Legal advice -  Child Contact flow 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#75]
@lucymk  link to the gov.uk website is currently not working 

please can we make this the link that the chat takes users to 

https://www.gov.uk/looking-after-children-divorce/types-of-court-order

**Comment by lucymk** [comment]
addressed

**Comment by joannayoungs** [comment]
@lucymk 

Link works fab - just another hopefully little thing if possible please 

Current - 
This order will state where your child lives and when your child spends time with each parent. You can apply for this court order through solicitor. To find a solicitor near you please visit: http://solicitors.lawsociety.org.uk/

You can find more information about Child Arrangement orders here: https://www.gov.uk/looking-after-children-divorce/types-of-court-order



Changed - (could we swap them over as feel like this will make more sense) 

You can find more information about Child Arrangement Orders here: https://www.gov.uk/looking-after-children-divorce/types-of-court-order

This order will state where your child lives and when your child spends time with each parent. You can apply for this court order through solicitor. To find a solicitor near you please visit: http://solicitors.lawsociety.org.uk/

**Comment by lucymk** [comment]
done! 👍
