### ISSUE TITLE
Legal advice - Child contact - wording 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#77]
Could we just change this bit below a little - 

Now - If you are having problems arranging child contact with the other parent of your child you can apply for a court order called a Child arrangement order

Could this part all be capitalised and a comma added so it reads: 
Changed - If you are having problems arranging child contact with the other parent of your child, you can apply for a court order called a Child Arrangements Order
 
thanks @lucymk

**Comment by lucymk** [comment]
addressed
