### ISSUE TITLE
Legal advice - Child contact flow - altering the wording slightly 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#78]
Currently - This will state where your child lives and when your child spends time with each parent. This can be applied for through a Solicitor. Please see "Accessing a solicitor" on where to find a solicitor.  

Changed - This order will state where your child lives and when your child spends time with each parent.  You can apply for this court order through solicitor. To find a solicitor near you please visit: http://solicitors.lawsociety.org.uk/ 

Thanks @lucymk

**Comment by lucymk** [comment]
addressed
