### ISSUE TITLE
Housing - no housing needed tonight- private flow 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#79]
Currently - 
You can speak to your letting agent or landlord to see if you are able to cut your tenancy short to enable you to move out due to the circumstances. There is more information at: www.shelter.org.uk
The housing and homelessness charity

If you would like more information on your housing options then please visit the Shelter website: www.shelter.org.uk
The housing and homelessness charity

Changed - 
You might be able to agree with your landlord/ letting agent to end your tenancy early. This is called 'surrendering your tenancy' and will enable you move out of the property if it is no longer safe for you to stay there. You can find out more information regarding your options and legal rights at www.shelter.org.uk

Can we remove the second pop up offering the link to shelter please :) 
Thanks @lucymk

**Comment by lucymk** [comment]
@joannayoungs I've addressed all these issues, please check it out and close if you're happy with them 😃
