### ISSUE TITLE
Calendly 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#80]
Hi @lucymk  just had a look on the invision link to have a look at the designs that Noga did. I noticed that when it takes you through to the calendly page to book an appointment it shows Fiamma Pather at the top. Is this an account she has created? I cant see any details of this anywhere.   
![image](https://user-images.githubusercontent.com/44438071/49456133-64c27280-f7e0-11e8-89f2-c430c32560c8.png)

**Comment by lucymk** [comment]
@joannayoungs hehe no, I created it with my email and just changed the name to hers to make it more realistic in the designs 😆 I can change it back though!

**Comment by joannayoungs** [comment]
Ah that makes sense! No worries, it was just I wanted to check it wasn't account details we needed to note down 😄
