### ISSUE TITLE
Log out button 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#83]
'Log out here' button not currently working, will let you hover and the mouse changes but when you click nothing happens. 

![image](https://user-images.githubusercontent.com/44438071/52425492-02ddfc00-2af4-11e9-8e0a-cb4da3034612.png)

**Comment by lucymk** [comment]
@joannayoungs please test and close if working now!

**Comment by joannayoungs** [comment]
Seems to be working fine now, thanks Lucy
