### ISSUE TITLE
Ellipsis 

### ISSUE THREAD

**Issue by joannayoungs** [InFact-coop/your-sanctuary#85]
Is it possible to show any ellipsis while we are typing? 

I have added it to a couple of the pre scripted sections of text already, but when we are live chatting I couldnt see if there is a setting for the live chat, dont know if you have any ideas? 
We can see them typing but would be great if they could see us typing too so they know we are responding!

**Comment by lucymk** [comment]
@joannayoungs I've done a bit of research and tested it out, and I actually think this is already happening.

**Comment by joannayoungs** [comment]
Ah in which case, that's great! When someone tested it in the office the other day it wasn't showing on their computer but I have also tried it and it seems to be working fine.
